### ISSUE TITLE
My Release Proposal for Envied

### ISSUE THREAD

**Issue by javierjulio** [eval/envied#29]
# Release Proposal

Hi Gert (@eval) I came across Envied through [your blog post](http://www.gertgoet.com/2014/10/14/envied-or-how-i-stopped-worrying-about-ruby-s-env.html) a few months after you shared it and just like yourself I was embracing the [twelve-factor methodology](https://12factor.net/config) since I felt the pain of configuring apps in multiple environments. I took to Envied quickly since its intuitive and easy to set up and work with. I'm using it in multiple production apps. I'm already benefiting from not just your contributions but others that have submitted pull requests. Since I love using Envied, I want to help contribute in keeping the project up to date. If you are not able to manage the project anymore, I'm happy to take ownership so Envied can continue on as its a great yet simple utility in any developers' toolbox. To make my case I've come up with the following as a set of releases that I'd like to do to keep the project current. I would appreciate your feedback and from anyone else using this great library.

In the releases lined out below, I've created branches for each release that contain the necessary changes with passing tests as I have travis setup on my fork. I did **not** change the `version.rb` file on purpose so the output of `ENVied::VERSION` in each branch below will still be 0.8.1.

## 0.8.2

A quick release to fast track support for Rails 5 so others don't need to use a branch.

- [x] Adjust rack dependency (#25)

**Available at: https://github.com/javierjulio/envied/tree/v0.8.2**

## 0.9.0

Introduce a new feature and drop support for old and no longer supported versions of Ruby.

- [x] Drop support for Ruby 1.9 and 2.0 as [they are no longer supported](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/).
- [x] Fix typos (#24, #28) - the latter had a build failure but only on Ruby 1.9.3.
- [x] Add Float type (#30) - we already get this from Coercible
- [x] Add URI type (#22) - This is useful not just for a URL but to also set port or scheme individually:

    ```ruby
    # Assume the following in Envfile
    # variable :SITE_URI, :uri, default: 'https://localhost:9999'

    config.action_mailer.default_url_options = {
      protocol: ENVied.SITE_URI.scheme, 
      host: ENVied.SITE_URI.host
    }
    config.action_mailer.asset_host = ENVied.SITE_URI.to_s
    ```

**Available at: https://github.com/javierjulio/envied/tree/v0.9.0**

## 0.10.0

Rack dependency is not needed to support just parsing a query string. Its better to [keep dependencies as minimal as possible](http://www.mikeperham.com/2016/02/09/kill-your-dependencies/) and own that if we can, if its manageable which it can be.

- [x] Add simple query string parser to support existing [test](https://github.com/eval/envied/blob/cdaf3f1fdb2d932d6aa7ef3df1473f0e3af4c505/spec/envied_spec.rb#L298) [cases](https://github.com/eval/envied/blob/cdaf3f1fdb2d932d6aa7ef3df1473f0e3af4c505/spec/coercer_spec.rb#L84)
- [x] Remove Rack dependency (#19)
- [x] Set explicit jruby versions in `.travis.yml` since using "jruby" points to an old 1.7.x version.

**Available at: https://github.com/javierjulio/envied/tree/v0.10.0**

## Future releases

We have some issues with integer coercion where we need to decide if we want to either convert a float to an integer or throw an error in that case. Probably the former is best. Some other things to consider too, all listed below.

- Update extractor to account for interpolated strings (#21)
- Consider supporting multiple groups (#16)
- Drop coercible (hasn't been updated) and implement functionality locally
- Look into other submitted issues
- Consider going 1.0.0
- Update integer type to modify float into an integer value or raise an error (#31)
- Add integer test cases where a float is given (#31)

**Comment by rhys-vdw** [comment]
Oh, ENVied hasn't been updated in two years! We're using it regularly in production. Perhaps it's appropriate to fork?

**Comment by javierjulio** [comment]
@rhys-vdw I'm going to fork it because I need some new features added for things I've been working on. I'm thinking of doing a branch with each release version.

**Comment by rhys-vdw** [comment]
Hm. Well hopefully you can get collaborator status and release rights for this repo.

**Comment by rhys-vdw** [comment]
Re: release schedule. I'd recommend going to 1.0.0 after the first merge, and then follow strict semver after that. I'm not familiar with the source, but I doubt very much that it's not production ready (which a version of < 1.0.0 implies).

**Comment by javierjulio** [comment]
Thanks, I'm hoping to get that. I'd like to help relieve @eval from having to manage the repo if he doesn't have the time or interest too. I think that's a good idea. I've been using the gem in several Rails projects and I know others are too all in production. Its definitely production ready. It might be missing some helpful features but its ready.

**Comment by javierjulio** [comment]
I'm going to revise this because its not necessary to have rack as a dependency for just parsing a query string. The rack gem is used just for the hash variable type. I just learned we can use `CGI.parse` for the query string! This is great! We can kill off a dependency and just use pure Ruby. All tests pass by changing the `ENVied::Coercer.to_hash` method to do the following:

```ruby
    def to_hash(str)
      CGI.parse(str).map { |key, values| [key, values[0]] }.to_h
    end
```

**Comment by rhys-vdw** [comment]
Sounds reasonable. I'm happy to provide PRs for the issues I've raised. But only if the project is alive. Otherwise I'll just continue to work around them.

**Comment by javierjulio** [comment]
In my fork of Envied I have completed branches for each release I've listed in my proposal (links included) so others can start giving feedback. Each release contains all the same changes in the mentioned PRs with passing tests. Please give them a try and let me know what you think.

## 0.8.2 -> https://github.com/javierjulio/envied/tree/v0.8.2

Support for Rails 5 by adjusting rack dependency version range.

## 0.9.0 -> https://github.com/javierjulio/envied/tree/v0.9.0

Drops support for Ruby 1.9 and 2.0 and adds 2 new variable types: float and uri.

## 0.10.0 -> https://github.com/javierjulio/envied/tree/v0.10.0

Removes rack dependency entirely as it was only used for the hash variable type which this release introduces a Ruby stdlib solution using CGI. All existing test cases for this type pass. Updated travis to use explicit jruby versions because specifying just "jruby" uses an old 1.7 release line. I updated it to match what rack has so the same requirements are met.

**Comment by rhys-vdw** [comment]
Sounds great. Are you planning on an offical gem release?

**Comment by javierjulio** [comment]
@rhys-vdw no because I don't have committer access for official releases. Most I can do is support features in my fork so others can include them in their projects. I sent an email to @eval asking to let me help maintain the project.

**Comment by jandudulski** [comment]
How about #23 ? :)

**Comment by javierjulio** [comment]
@jandudulski yes I had seen your PR before I started and think its good but I was starting to realize then that we shouldn't need coercible. We should be able to implement that functionality without needing a dependency also because it doesn't seem that coercible is maintained. The data types that we use for coercible should be simple enough that we can kill off that dependency. I've been thinking of doing that for a future release. I just wanted to get out the most pressing issues now since several of these are holding people back.

**Comment by jandudulski** [comment]
@javierjulio sounds reasonable 👍

**Comment by eval** [comment]
Sorry about the inactivity guys. And great proposal @javierjulio - I added you as a collaborator. Let me know what you need and I'll help you get new releases out.

Thanks for your patience.

**Comment by javierjulio** [comment]
@eval thanks! I'm going to work on the first patch release.

**Comment by eval** [comment]
@javierjulio how about aiming for a 1.0 release with the points you mentioned?

**Comment by javierjulio** [comment]
@eval honestly besides 0.8.2, I wanted to go with all these changes at once. I'm big on staying up to date so I'm down with going 1.0. In regards to the note in your email, I have a solution for removing the rack dependency entirely which just [uses `CGI.parse`, part of the Ruby stdlib](https://github.com/javierjulio/envied/commit/66eb3e893588f1672becb286604f1199bbb91f38).

**Comment by eval** [comment]
> I have a solution for removing the rack dependency entirely which just uses CGI.parse, part of the Ruby stdlib.

Nice replacement indeed - let's go with that version!

**Comment by eval** [comment]
Already a new release - great stuff @javierjulio 🚢 👍

**Comment by ms-ati** [comment]
Fantastic open source collaboration here

**Comment by javierjulio** [comment]
I'm close to wrapping up everything here in master which will now be for a 1.0 release! 🎉❤️ I have a new issue for [planning the 1.0 release (#33)](#33) and collecting any ideas for the future as I work on it. If you have time I would love to get feedback from you all. Look forward to 1.0 soon!
