### ISSUE TITLE
Plans for 1.0 release 🎉

### ISSUE THREAD

**Issue by javierjulio** [eval/envied#33]
We want to get Envied to a 1.0 release soon as everything it offers is already stable. It's been used by many in production successfully. We want to clean up some things before cutting a final release. Feel free to share any input, even if its something we don't consider for 1.0, we'd like to know and have it in the pipeline for future releases. Keep in mind by going 1.0 we can introduce breaking changes with that release.

## 0.9.0 release

- [x] Add new types: `float` (#30) and `uri` (#22)
- [x] Update ENV extractor to find interpolated variables (#21)
- [x] Fix typos (#24 and #28)
- [x] Remove support for old Rubies (require Ruby 2.1+)
- [x] Replace rack dependency with stdlib solution using `CGI.parse` for hash type
- [x] Update all examples to use strings for defaults
- [x] Support multiple groups (#16)

## 1.0 release

- [x] Remove coercible dependency and implement what we need from it (#49)
- [ ] Replace `check:heroku` with standard json/diff support instead of Heroku explicitness
- [x] submit to [Ruby toolbox](https://github.com/rubytoolbox/catalog/pull/253)
- [x] remove defaults (#34 )
- [x] Drop support for EOL'ed versions of Ruby and JRuby (#48, #51)
- [x] Add strict integer coercion (#35)
- Consider requiring default values be strings for ENV domain consistency and raise error if default value is not a string e.g. `default: true` vs. `default: "true"`

## Ideas for future releases

- New take on default values and having parity with ENV (#34)
- Expose API to [register types in Envfile](https://github.com/eval/envied/issues/32#issuecomment-281677795)

**Comment by eval** [comment]
good stuff! - I created a milestone as well.

I got some more thoughts on defaults that I'd like some input on - will write an issue about it.

**Comment by eval** [comment]
@javierjulio I described it in #34

**Comment by javierjulio** [comment]
@eval I planned to commit these changes already since they are minor. What do you think about doing a minor release with those since they are valuable before going 1.0? Or perhaps move some of them to a 1.0 release?

**Comment by eval** [comment]
Sure, a new minor release sounds good.

**Comment by javierjulio** [comment]
Going to release 0.9.0 with what was outlined.

**Comment by eval** [comment]
Cool. I merged #35 as well.

**Comment by eval** [comment]
PR for Ruby toolbox pending: https://github.com/rubytoolbox/catalog/pull/253

**Comment by olleolleolle** [comment]
(I ticked the checkbox for the Ruby Toolbox PR, which is now _merged_!)
